export { Contact } from "./Contact";
export { Hero } from "./Hero";
export { About } from "./About";
export { USP } from "./USP";
export { Coaching } from "./Coaching";
export { Mediacio } from "./Mediacio";
export { Prices } from "./Prices";
export { Book } from "./Book";
export { Training } from "./Training";
export { Layout, BlogLayout, SEO } from "./Layout";
export { ScrollTo } from "./ScrollTo";
export { Link } from "./Link";
