backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://panderacoach.hu/

collections:
  - name: "irasaim" # Used in routes
    label: "Írásaim" # Used in the UI
    folder: "src/pages/irasaim" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article",
        }
      - { label: "Címsor", name: "title", widget: "string" }
      - { label: "Bevezető", name: "description", widget: "text" }
      - { label: "Kulcsszavak", name: "keywords", widget: "string" }
      - { label: "Dátum", name: "date", widget: "date", format: "YYYY-MM-DD" }
      - { label: "Kép", name: "image", widget: image }
      - { label: "Tartalom", name: "body", widget: "markdown" }
